#!/usr/bin/env npx tsx
/**
 * FerroUI Design Token Build Pipeline
 *
 * Reads primitive, semantic, and component token JSON files and generates:
 *   1. CSS custom properties (dist/tokens.css)
 *   2. Tailwind theme config (dist/tailwind-tokens.js)
 *   3. TypeScript constants (dist/tokens.ts)
 *
 * Usage: npx tsx tokens/build.ts
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DIST = path.join(__dirname, 'dist');

// ── Types ───────────────────────────────────────────────────────────────────
type TokenEntry = { $value: string | string[]; $type: string };
type TokenFile = Record<string, any>;
type FlattenedTokens = Record<string, TokenEntry>;

// ── Helpers ─────────────────────────────────────────────────────────────────
function flatten(obj: any, prefix = ''): FlattenedTokens {
  const result: FlattenedTokens = {};
  for (const key in obj) {
    const fullKey = prefix ? `${prefix}.${key}` : key;
    if (obj[key] && typeof obj[key] === 'object' && '$value' in obj[key]) {
      result[fullKey] = obj[key] as TokenEntry;
    } else if (obj[key] && typeof obj[key] === 'object') {
      Object.assign(result, flatten(obj[key], fullKey));
    }
  }
  return result;
}

function loadDir(dir: string): TokenFile {
  const merged: TokenFile = {};
  if (!fs.existsSync(dir)) return merged;
  for (const file of fs.readdirSync(dir).filter((f: string) => f.endsWith('.json'))) {
    const data = JSON.parse(fs.readFileSync(path.join(dir, file), 'utf-8'));
    // Simple top-level merge is enough for our current structure
    for (const key in data) {
      if (typeof data[key] === 'object' && !('$value' in data[key]) && merged[key]) {
        Object.assign(merged[key], data[key]);
      } else {
        merged[key] = data[key];
      }
    }
  }
  return merged;
}

// Convert dotted name to kebab-case for CSS
function toKebab(name: string): string {
  return name.replace(/\./g, '-');
}

// ── Load tokens ─────────────────────────────────────────────────────────────
const primitiveData = loadDir(path.join(__dirname, 'primitive'));
const primitives = flatten(primitiveData);

const semanticData = loadDir(path.join(__dirname, 'semantic'));
// semanticData is { light: { color: ... }, dark: { color: ... }, ... }

const componentData = loadDir(path.join(__dirname, 'component'));
const components = flatten(componentData);

// ── Resolve references ──────────────────────────────────────────────────────
function resolve(value: string | string[], ctx: FlattenedTokens): string {
  if (Array.isArray(value)) {
    return value.map(v => resolve(v, ctx)).join(', ');
  }
  return value.replace(/\{([^}]+)\}/g, (_, ref) => {
    const entry = ctx[ref];
    if (entry) {
      return resolve(entry.$value, ctx);
    }
    // Fallback to CSS variable if not found in context
    return `var(--${toKebab(ref)})`;
  });
}

// ── 1. Generate CSS ─────────────────────────────────────────────────────────
function generateCSS(): string {
  const lines: string[] = ['/* Auto-generated by tokens/build.ts — do not edit */'];

  lines.push(':root {');
  for (const [name, entry] of Object.entries(primitives)) {
    const val = Array.isArray(entry.$value) ? entry.$value.join(', ') : entry.$value;
    lines.push(`  --${toKebab(name)}: ${val};`);
  }
  lines.push('}');

  // Semantic themes
  const themeNames = Object.keys(semanticData);
  for (const theme of themeNames) {
    const themeTokens = flatten(semanticData[theme]);
    const selector = theme === 'light' ? ':root' : `[data-theme="${theme}"]`;
    lines.push(`${selector} {`);
    for (const [name, entry] of Object.entries(themeTokens)) {
      lines.push(`  --${toKebab(name)}: ${resolve(entry.$value, primitives)};`);
    }
    lines.push('}');
  }

  // Component tokens
  lines.push('/* Component tokens */');
  lines.push(':root {');
  const lightSemantic = flatten(semanticData['light'] || {});
  for (const [name, entry] of Object.entries(components)) {
    lines.push(`  --${toKebab(name)}: ${resolve(entry.$value, { ...primitives, ...lightSemantic })};`);
  }
  lines.push('}');

  return lines.join('\n');
}

// ── 2. Generate Tailwind config ─────────────────────────────────────────────
function generateTailwind(): string {
  const colors: Record<string, string> = {};
  const spacing: Record<string, string> = {};
  const fontSize: Record<string, string> = {};
  const borderRadius: Record<string, string> = {};
  const boxShadow: Record<string, string> = {};

  // We use primitive keys for Tailwind map
  for (const [name, entry] of Object.entries(primitives)) {
    const varName = `var(--${toKebab(name)})`;
    const key = toKebab(name);
    switch (entry.$type) {
      case 'color': colors[key] = varName; break;
      case 'dimension': 
        if (name.startsWith('space')) spacing[key] = varName;
        if (name.startsWith('radius')) borderRadius[key] = varName;
        break;
      case 'spacing': spacing[key] = varName; break;
      case 'fontSize': fontSize[key] = varName; break;
      case 'borderRadius': borderRadius[key] = varName; break;
      case 'shadow': boxShadow[key] = varName; break;
    }
  }

  const obj = { colors, spacing, fontSize, borderRadius, boxShadow };
  return `// Auto-generated by tokens/build.ts — do not edit\nmodule.exports = ${JSON.stringify(obj, null, 2)};\n`;
}

// ── 3. Generate TypeScript ──────────────────────────────────────────────────
function generateTS(): string {
  const lines: string[] = ['// Auto-generated by tokens/build.ts — do not edit'];

  lines.push('export const primitiveTokens = {');
  for (const [name, entry] of Object.entries(primitives)) {
    const val = Array.isArray(entry.$value) ? entry.$value.join(', ') : entry.$value;
    lines.push(`  '${name}': '${val}',`);
  }
  lines.push('} as const;\n');

  lines.push('export const semanticTokens = {');
  const lightSemantic = flatten(semanticData['light'] || {});
  for (const [name] of Object.entries(lightSemantic)) {
    lines.push(`  '${name}': 'var(--${toKebab(name)})',`);
  }
  lines.push('} as const;\n');

  lines.push('export const componentTokens = {');
  for (const [name] of Object.entries(components)) {
    lines.push(`  '${name}': 'var(--${toKebab(name)})',`);
  }
  lines.push('} as const;\n');

  return lines.join('\n');
}

// ── Build ───────────────────────────────────────────────────────────────────
fs.mkdirSync(DIST, { recursive: true });

fs.writeFileSync(path.join(DIST, 'tokens.css'), generateCSS(), 'utf-8');
console.log('✔ tokens/dist/tokens.css');

fs.writeFileSync(path.join(DIST, 'tailwind-tokens.js'), generateTailwind(), 'utf-8');
console.log('✔ tokens/dist/tailwind-tokens.js');

fs.writeFileSync(path.join(DIST, 'tokens.ts'), generateTS(), 'utf-8');
console.log('✔ tokens/dist/tokens.ts');

console.log('\nDone — token build complete.');
