/**
 * FerroUI Design Tokens
 * 
 * This file is a placeholder for TypeDoc discovery. 
 * The actual tokens are generated by scripts/build-tokens.ts into dist/tokens.ts.
 */

export * from '../dist/tokens.js';
