#!/usr/bin/env npx tsx
/**
 * Alloy Design Token Build Pipeline
 *
 * Reads primitive, semantic, and component token JSON files and generates:
 *   1. CSS custom properties (dist/tokens.css)
 *   2. Tailwind theme config (dist/tailwind-tokens.js)
 *   3. TypeScript constants (dist/tokens.ts)
 *
 * Usage: npx tsx tokens/build.ts
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DIST = path.join(__dirname, 'dist');

// ── Load tokens ─────────────────────────────────────────────────────────────
type TokenEntry = { $value: string; $type: string };
type TokenFile = Record<string, TokenEntry>;

function loadDir(dir: string): TokenFile {
  const merged: TokenFile = {};
  if (!fs.existsSync(dir)) return merged;
  for (const file of fs.readdirSync(dir).filter((f: string) => f.endsWith('.json'))) {
    const data = JSON.parse(fs.readFileSync(path.join(dir, file), 'utf-8')) as TokenFile;
    Object.assign(merged, data);
  }
  return merged;
}

const primitives = loadDir(path.join(__dirname, 'primitive'));
const semanticLight = loadDir(path.join(__dirname, 'semantic'));
const components = loadDir(path.join(__dirname, 'component'));

// ── Resolve references ──────────────────────────────────────────────────────
function resolve(value: string, ctx: TokenFile): string {
  return value.replace(/\{([^}]+)\}/g, (_, ref) => {
    const entry = ctx[ref];
    return entry ? resolve(entry.$value, ctx) : `var(--${ref})`;
  });
}

// ── 1. Generate CSS ─────────────────────────────────────────────────────────
function generateCSS(): string {
  const lines: string[] = ['/* Auto-generated by tokens/build.ts — do not edit */'];

  lines.push(':root {');
  for (const [name, entry] of Object.entries(primitives)) {
    lines.push(`  --${name}: ${entry.$value};`);
  }
  lines.push('}');

  // Semantic themes
  const themes: Record<string, string> = {
    light: 'semantic/light.json',
    dark: 'semantic/dark.json',
    'high-contrast': 'semantic/high-contrast.json',
    enterprise: 'semantic/enterprise.json',
  };

  for (const [theme, file] of Object.entries(themes)) {
    const filePath = path.join(__dirname, file);
    if (!fs.existsSync(filePath)) continue;
    const data = JSON.parse(fs.readFileSync(filePath, 'utf-8')) as TokenFile;
    const selector = theme === 'light' ? ':root' : `[data-theme="${theme}"]`;
    lines.push(`${selector} {`);
    for (const [name, entry] of Object.entries(data)) {
      lines.push(`  --${name}: ${resolve(entry.$value, primitives)};`);
    }
    lines.push('}');
  }

  // Component tokens
  lines.push('/* Component tokens */');
  lines.push(':root {');
  for (const [name, entry] of Object.entries(components)) {
    lines.push(`  --${name}: ${resolve(entry.$value, { ...primitives, ...semanticLight })};`);
  }
  lines.push('}');

  return lines.join('\n');
}

// ── 2. Generate Tailwind config ─────────────────────────────────────────────
function generateTailwind(): string {
  const colors: Record<string, string> = {};
  const spacing: Record<string, string> = {};
  const fontSize: Record<string, string> = {};
  const borderRadius: Record<string, string> = {};
  const boxShadow: Record<string, string> = {};

  for (const [name, entry] of Object.entries(primitives)) {
    const val = `var(--${name})`;
    switch (entry.$type) {
      case 'color': colors[name] = val; break;
      case 'spacing': spacing[name] = val; break;
      case 'fontSize': fontSize[name] = val; break;
      case 'borderRadius': borderRadius[name] = val; break;
      case 'shadow': boxShadow[name] = val; break;
    }
  }

  const obj = { colors, spacing, fontSize, borderRadius, boxShadow };
  return `// Auto-generated by tokens/build.ts — do not edit\nmodule.exports = ${JSON.stringify(obj, null, 2)};\n`;
}

// ── 3. Generate TypeScript ──────────────────────────────────────────────────
function generateTS(): string {
  const lines: string[] = ['// Auto-generated by tokens/build.ts — do not edit'];

  lines.push('export const primitiveTokens = {');
  for (const [name, entry] of Object.entries(primitives)) {
    lines.push(`  '${name}': '${entry.$value}',`);
  }
  lines.push('} as const;\n');

  lines.push('export const semanticTokens = {');
  for (const [name] of Object.entries(semanticLight)) {
    lines.push(`  '${name}': 'var(--${name})',`);
  }
  lines.push('} as const;\n');

  lines.push('export const componentTokens = {');
  for (const [name] of Object.entries(components)) {
    lines.push(`  '${name}': 'var(--${name})',`);
  }
  lines.push('} as const;\n');

  return lines.join('\n');
}

// ── Build ───────────────────────────────────────────────────────────────────
fs.mkdirSync(DIST, { recursive: true });

fs.writeFileSync(path.join(DIST, 'tokens.css'), generateCSS(), 'utf-8');
console.log('✔ tokens/dist/tokens.css');

fs.writeFileSync(path.join(DIST, 'tailwind-tokens.js'), generateTailwind(), 'utf-8');
console.log('✔ tokens/dist/tailwind-tokens.js');

fs.writeFileSync(path.join(DIST, 'tokens.ts'), generateTS(), 'utf-8');
console.log('✔ tokens/dist/tokens.ts');

console.log('\nDone — token build complete.');
