import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TOKENS_DIR = __dirname;
const OUT_DIR = path.resolve(__dirname, '../apps/web/src/styles');

interface Token {
  $value: string;
  $type: string;
}

type TokenMap = Record<string, Token>;

function loadJson(filePath: string): TokenMap {
  return JSON.parse(fs.readFileSync(filePath, 'utf-8')) as TokenMap;
}

function loadPrimitives(): TokenMap {
  const primDir = path.join(TOKENS_DIR, 'primitive');
  const files = fs.readdirSync(primDir).filter(f => f.endsWith('.json'));
  let result: TokenMap = {};
  for (const f of files) {
    const data = loadJson(path.join(primDir, f));
    result = { ...result, ...data };
  }
  return result;
}

function resolveReference(value: string, primitives: TokenMap): string {
  const match = value.match(/^\{(.+)\}$/);
  if (!match) return value;
  const ref = match[1];
  const prim = primitives[ref];
  if (!prim) {
    console.warn(`[tokens] Unresolved reference: {${ref}}`);
    return value;
  }
  return prim.$value;
}

function tokenNameToCssVar(name: string): string {
  return `--alloy-${name}`;
}

function buildTheme(semanticFile: string, primitives: TokenMap): string {
  const semanticTokens = loadJson(semanticFile);
  const vars: string[] = [];

  for (const [name, token] of Object.entries(semanticTokens)) {
    const resolved = resolveReference(token.$value, primitives);
    vars.push(`  ${tokenNameToCssVar(name)}: ${resolved};`);
  }

  return vars.join('\n');
}

function buildPrimitiveVars(primitives: TokenMap): string {
  return Object.entries(primitives)
    .map(([name, token]) => `  ${tokenNameToCssVar(name)}: ${token.$value};`)
    .join('\n');
}

function build(): void {
  const primitives = loadPrimitives();
  const lightTokens = loadJson(path.join(TOKENS_DIR, 'semantic/light.json'));
  const darkTokens = loadJson(path.join(TOKENS_DIR, 'semantic/dark.json'));

  const lightVars = buildTheme(path.join(TOKENS_DIR, 'semantic/light.json'), primitives);
  const darkVars = buildTheme(path.join(TOKENS_DIR, 'semantic/dark.json'), primitives);
  const primitiveVars = buildPrimitiveVars(primitives);

  const css = `/* AUTO-GENERATED by tokens/build.ts — DO NOT EDIT MANUALLY */

:root {
${primitiveVars}

${lightVars}
}

[data-theme="dark"] {
${darkVars}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${darkVars.split('\n').map(l => '  ' + l).join('\n')}
  }
}
`;

  if (!fs.existsSync(OUT_DIR)) {
    fs.mkdirSync(OUT_DIR, { recursive: true });
  }

  const outFile = path.join(OUT_DIR, 'tokens.css');
  fs.writeFileSync(outFile, css, 'utf-8');
  console.log(`[tokens] Written ${Object.keys(primitives).length} primitives + ${Object.keys(lightTokens).length} semantic tokens → ${outFile}`);

  const tsOut = `/* AUTO-GENERATED by tokens/build.ts — DO NOT EDIT MANUALLY */
export const tokens = ${JSON.stringify({ primitive: primitives, semantic: { light: lightTokens, dark: darkTokens } }, null, 2)} as const;
`;
  const tsFile = path.join(OUT_DIR, 'tokens.ts');
  fs.writeFileSync(tsFile, tsOut, 'utf-8');
  console.log(`[tokens] TypeScript token exports → ${tsFile}`);
}

build();
