/* AUTO-GENERATED by tokens/build.ts — DO NOT EDIT MANUALLY */
export const tokens = {
  "primitive": {
    "0": {
      "$value": "0px",
      "$type": "spacing"
    },
    "1": {
      "$value": "4px",
      "$type": "spacing"
    },
    "2": {
      "$value": "8px",
      "$type": "spacing"
    },
    "3": {
      "$value": "12px",
      "$type": "spacing"
    },
    "4": {
      "$value": "16px",
      "$type": "spacing"
    },
    "5": {
      "$value": "20px",
      "$type": "spacing"
    },
    "6": {
      "$value": "24px",
      "$type": "spacing"
    },
    "8": {
      "$value": "32px",
      "$type": "spacing"
    },
    "10": {
      "$value": "40px",
      "$type": "spacing"
    },
    "12": {
      "$value": "48px",
      "$type": "spacing"
    },
    "16": {
      "$value": "64px",
      "$type": "spacing"
    },
    "blue-50": {
      "$value": "#eff6ff",
      "$type": "color"
    },
    "blue-100": {
      "$value": "#dbeafe",
      "$type": "color"
    },
    "blue-500": {
      "$value": "#3b82f6",
      "$type": "color"
    },
    "blue-600": {
      "$value": "#2563eb",
      "$type": "color"
    },
    "blue-700": {
      "$value": "#1d4ed8",
      "$type": "color"
    },
    "gray-50": {
      "$value": "#f9fafb",
      "$type": "color"
    },
    "gray-100": {
      "$value": "#f3f4f6",
      "$type": "color"
    },
    "gray-200": {
      "$value": "#e5e7eb",
      "$type": "color"
    },
    "gray-600": {
      "$value": "#4b5563",
      "$type": "color"
    },
    "gray-700": {
      "$value": "#374151",
      "$type": "color"
    },
    "gray-800": {
      "$value": "#1f2937",
      "$type": "color"
    },
    "gray-900": {
      "$value": "#111827",
      "$type": "color"
    },
    "white": {
      "$value": "#ffffff",
      "$type": "color"
    },
    "red-500": {
      "$value": "#ef4444",
      "$type": "color"
    },
    "red-600": {
      "$value": "#dc2626",
      "$type": "color"
    },
    "green-500": {
      "$value": "#22c55e",
      "$type": "color"
    },
    "yellow-500": {
      "$value": "#eab308",
      "$type": "color"
    },
    "font-family-sans": {
      "$value": "'Inter', 'system-ui', sans-serif",
      "$type": "fontFamily"
    },
    "font-family-mono": {
      "$value": "'JetBrains Mono', 'Fira Code', monospace",
      "$type": "fontFamily"
    },
    "font-size-xs": {
      "$value": "12px",
      "$type": "fontSize"
    },
    "font-size-sm": {
      "$value": "14px",
      "$type": "fontSize"
    },
    "font-size-base": {
      "$value": "16px",
      "$type": "fontSize"
    },
    "font-size-lg": {
      "$value": "18px",
      "$type": "fontSize"
    },
    "font-size-xl": {
      "$value": "20px",
      "$type": "fontSize"
    },
    "font-size-2xl": {
      "$value": "24px",
      "$type": "fontSize"
    },
    "font-size-3xl": {
      "$value": "30px",
      "$type": "fontSize"
    },
    "font-weight-normal": {
      "$value": "400",
      "$type": "fontWeight"
    },
    "font-weight-medium": {
      "$value": "500",
      "$type": "fontWeight"
    },
    "font-weight-semibold": {
      "$value": "600",
      "$type": "fontWeight"
    },
    "font-weight-bold": {
      "$value": "700",
      "$type": "fontWeight"
    },
    "line-height-tight": {
      "$value": "1.25",
      "$type": "lineHeight"
    },
    "line-height-normal": {
      "$value": "1.5",
      "$type": "lineHeight"
    },
    "line-height-relaxed": {
      "$value": "1.75",
      "$type": "lineHeight"
    }
  },
  "semantic": {
    "light": {
      "color-background": {
        "$value": "{white}",
        "$type": "color"
      },
      "color-background-subtle": {
        "$value": "{gray-50}",
        "$type": "color"
      },
      "color-surface": {
        "$value": "{white}",
        "$type": "color"
      },
      "color-border": {
        "$value": "{gray-200}",
        "$type": "color"
      },
      "color-text-primary": {
        "$value": "{gray-900}",
        "$type": "color"
      },
      "color-text-secondary": {
        "$value": "{gray-600}",
        "$type": "color"
      },
      "color-text-muted": {
        "$value": "{gray-600}",
        "$type": "color"
      },
      "color-brand": {
        "$value": "{blue-600}",
        "$type": "color"
      },
      "color-brand-hover": {
        "$value": "{blue-700}",
        "$type": "color"
      },
      "color-brand-subtle": {
        "$value": "{blue-50}",
        "$type": "color"
      },
      "color-error": {
        "$value": "{red-600}",
        "$type": "color"
      },
      "color-success": {
        "$value": "{green-500}",
        "$type": "color"
      },
      "color-warning": {
        "$value": "{yellow-500}",
        "$type": "color"
      },
      "space-xs": {
        "$value": "{1}",
        "$type": "spacing"
      },
      "space-sm": {
        "$value": "{2}",
        "$type": "spacing"
      },
      "space-md": {
        "$value": "{4}",
        "$type": "spacing"
      },
      "space-lg": {
        "$value": "{6}",
        "$type": "spacing"
      },
      "space-xl": {
        "$value": "{8}",
        "$type": "spacing"
      },
      "space-2xl": {
        "$value": "{12}",
        "$type": "spacing"
      },
      "font-body": {
        "$value": "{font-family-sans}",
        "$type": "fontFamily"
      },
      "font-code": {
        "$value": "{font-family-mono}",
        "$type": "fontFamily"
      },
      "text-body": {
        "$value": "{font-size-base}",
        "$type": "fontSize"
      },
      "text-small": {
        "$value": "{font-size-sm}",
        "$type": "fontSize"
      },
      "text-heading": {
        "$value": "{font-size-2xl}",
        "$type": "fontSize"
      }
    },
    "dark": {
      "color-background": {
        "$value": "{gray-900}",
        "$type": "color"
      },
      "color-background-subtle": {
        "$value": "{gray-800}",
        "$type": "color"
      },
      "color-surface": {
        "$value": "{gray-800}",
        "$type": "color"
      },
      "color-border": {
        "$value": "{gray-700}",
        "$type": "color"
      },
      "color-text-primary": {
        "$value": "{white}",
        "$type": "color"
      },
      "color-text-secondary": {
        "$value": "{gray-200}",
        "$type": "color"
      },
      "color-text-muted": {
        "$value": "{gray-200}",
        "$type": "color"
      },
      "color-brand": {
        "$value": "{blue-500}",
        "$type": "color"
      },
      "color-brand-hover": {
        "$value": "{blue-600}",
        "$type": "color"
      },
      "color-brand-subtle": {
        "$value": "{gray-800}",
        "$type": "color"
      },
      "color-error": {
        "$value": "{red-500}",
        "$type": "color"
      },
      "color-success": {
        "$value": "{green-500}",
        "$type": "color"
      },
      "color-warning": {
        "$value": "{yellow-500}",
        "$type": "color"
      },
      "space-xs": {
        "$value": "{1}",
        "$type": "spacing"
      },
      "space-sm": {
        "$value": "{2}",
        "$type": "spacing"
      },
      "space-md": {
        "$value": "{4}",
        "$type": "spacing"
      },
      "space-lg": {
        "$value": "{6}",
        "$type": "spacing"
      },
      "space-xl": {
        "$value": "{8}",
        "$type": "spacing"
      },
      "space-2xl": {
        "$value": "{12}",
        "$type": "spacing"
      },
      "font-body": {
        "$value": "{font-family-sans}",
        "$type": "fontFamily"
      },
      "font-code": {
        "$value": "{font-family-mono}",
        "$type": "fontFamily"
      },
      "text-body": {
        "$value": "{font-size-base}",
        "$type": "fontSize"
      },
      "text-small": {
        "$value": "{font-size-sm}",
        "$type": "fontSize"
      },
      "text-heading": {
        "$value": "{font-size-2xl}",
        "$type": "fontSize"
      }
    }
  }
} as const;
