import * as crypto from 'node:crypto';

/**
 * Signer utility for Ed25519 signing and verification.
 * Used for Content Provenance (C2PA) to verify that layouts
 * were generated by a legitimate FerroUI engine.
 */
export class Signer {
  /**
   * Generates an Ed25519 key pair for signing.
   * In a production environment, these keys should be stored
   * securely in a Key Management Service (KMS).
   */
  static generateKeyPair(): { publicKey: string; privateKey: string } {
    const { publicKey, privateKey } = crypto.generateKeyPairSync('ed25519', {
      publicKeyEncoding: { type: 'spki', format: 'pem' },
      privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
    });
    return { publicKey, privateKey };
  }

  /**
   * Signs a data string using an Ed25519 private key.
   * 
   * @param data The string content to sign
   * @param privateKey The Ed25519 private key in PEM format
   * @returns The signature in base64 format
   */
  static sign(data: string, privateKey: string): string {
    const signature = crypto.sign(null, Buffer.from(data), privateKey);
    return signature.toString('base64');
  }

  /**
   * Verifies an Ed25519 signature.
   * 
   * @param data The original string content
   * @param signature The signature in base64 format
   * @param publicKey The Ed25519 public key in PEM format
   * @returns True if the signature is valid
   */
  static verify(data: string, signature: string, publicKey: string): boolean {
    try {
      return crypto.verify(
        null, 
        Buffer.from(data), 
        publicKey, 
        Buffer.from(signature, 'base64')
      );
    } catch {
      return false;
    }
  }
}
